export const IGNORE_HOSTNAME_URL_MATCHER = {
  label: 'Ignore hostname',
  value: 'IGNORE_HOSTNAME'
}

export const URL_MATCHER_TYPES = [
  IGNORE_HOSTNAME_URL_MATCHER,
  {
    label: 'Match hostname',
    value: 'MATCH_HOSTNAME'
  }
]

export const DEFAULT_URL_MATCHER_TYPE = IGNORE_HOSTNAME_URL_MATCHER.value

export enum STORAGE_KEYS {
  NETWORK_MOCKS = 'NETWORK_MOCKS',
  RUNTIME_EVENTS = 'RUNTIME_EVENTS',
  PREFERENCE_SETTINGS = 'PREFERENCE_SETTINGS',
  RUNTIME_ERRORS = 'RUNTIME_ERRORS'
}

export type STORAGE_KEYS_STRINGS = keyof typeof STORAGE_KEYS
